import { agentError, isAgentError } from './errors'
import { parseAnalyzeContext } from './context-schema'
import type { BlockMatchContext } from './report-block-registry'
import { getScene, instantiateScene, REPORT_SCENES, sceneInfo } from './report-scene-registry'
import { fail, readJson, requiredFlag, stringFlag, writeOutput } from './cli-utils'
import { templateSpecToYaml } from './report-template-registry'
import type { CliArgs } from './cli-utils'

export function runScene(args: CliArgs): unknown {
  const action = args.positional[0]
  if (action === 'list') return { ok: true, value: REPORT_SCENES.map(scene => sceneInfo(scene)) }
  const id = args.positional[1]
  if (!id) return fail(agentError('MISSING_INPUT', `Usage: miao-viz spec scene ${action ?? 'inspect'} <scene-id>`))
  const scene = getScene(id)
  if (!scene) {
    return fail(agentError('UNKNOWN_SCENE_ID', `Scene '${id}' was not found.`, {
      availableIds: REPORT_SCENES.map(item => item.id)
    }))
  }
  if (action === 'inspect') return { ok: true, value: sceneInfo(scene) }
  if (action !== 'instantiate') {
    return fail(agentError('UNKNOWN_SUBCOMMAND', `Unknown scene action '${action}'. Supported: list, inspect, instantiate`))
  }
  const contextPath = requiredFlag(args, 'context')
  if (isAgentError(contextPath)) return fail(contextPath)
  const context = parseAnalyzeContext(readJson<unknown>(contextPath))
  if (!context) return fail(agentError('INVALID_CONTEXT', 'context.json format is invalid.', { contextPath }))
  const matchCtx: BlockMatchContext = {
    fields: context.fields, evidence: context.evidence, catalog: context.catalog,
    sampleWarnings: context.sampleWarnings, metricCandidates: context.metricCandidates
  }
  const decision = scene.canUse(matchCtx)
  if (!decision.ok) {
    return fail(agentError('SCENE_NOT_APPLICABLE', `Scene '${id}' cannot be used: ${decision.reason}`, {
      sceneId: id, reason: decision.reason, missing: decision.missing,
      clarificationQuestions: decision.clarificationQuestions
    }))
  }
  const spec = instantiateScene(scene, matchCtx)
  if (!spec) {
    return fail(agentError('SCENE_TEMPLATE_NOT_APPLICABLE', `No template for scene '${id}' is applicable.`, {
      sceneId: id, templateIds: scene.templates
    }))
  }
  const yaml = [
    `# Generated by: miao-viz spec scene instantiate ${id}`,
    `# Scene: ${scene.name} (score: ${decision.score.toFixed(2)})`,
    '# Review generated insights and validate with --context --verify --strict',
    '', templateSpecToYaml(spec)
  ].join('\n')
  const output = stringFlag(args, 'output')
  if (output) {
    writeOutput(output, yaml)
    return { ok: true, value: { output, sceneId: id, score: decision.score } }
  }
  return { ok: true, value: { yaml, sceneId: id, score: decision.score } }
}
